import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/ui/dashboard/Sidebar/Sidebar";
import HeroLogo from "@/ui/assets/images/icon-128x128.png";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div>
            <div className="flex justify-start">
              <Image
                src={HeroLogo}
                alt="Digital Media Co. Logo"
                className="h-20 w-80 mb-2 border rounded-lg"
              />
            </div>
            <div className="">
              <Sidebar />
            </div>
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
